using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OXDesk.Core.AuditLogs;

/// <summary>
/// Represents an audit log entry in the CRM system.
/// Pure domain entity for tracking system activities.
/// </summary>
[Table("audit_logs")]
public class AuditLog
{
    /// <summary>
    /// Gets or sets the unique identifier for the audit log entry.
    /// </summary>
    [Key]
    [Column("id")]
    [Required]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }
    
    /// <summary>
    /// Gets or sets the tenant identifier.
    /// </summary>
    [Column("tenant_id")]
    [Required]
    public int TenantId { get; set; }

    /// <summary>
    /// Gets or sets the object key/entity type that was affected.
    /// </summary>
    [Column("module")]
    [Required]
    [MaxLength(100)]
    public string ObjectKey { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the event/action that occurred.
    /// </summary>
    [Column("event")]
    [Required]
    [MaxLength(100)]
    public string Event { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the ID of the entity that was affected.
    /// </summary>
    [Column("mapped_id")]
    [Required]
    public int ObjectItemId { get; set; }

    /// <summary>
    /// Gets or sets the IP address from which the action was performed.
    /// </summary>
    [Column("ip")]
    [MaxLength(45)]
    public string IP { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the any data generated for the action.
    /// </summary>
    [Column("data")]
    [MaxLength(1000)]
    public string? Data { get; set; }

    /// <summary>
    /// Gets or sets the date and time when the audit log was created.
    /// </summary>
    [Column("created_at")]
    [Required]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Gets or sets the user who performed the action.
    /// </summary>
    [Column("created_by")]
    [Required]
    public int CreatedBy { get; set; }


    /// <summary>
    /// Initializes a new instance of the <see cref="AuditLog"/> class.
    /// Default constructor for Entity Framework and general use.
    /// </summary>
    public AuditLog() { }

    /// <summary>
    /// Initializes a new instance of the <see cref="AuditLog"/> class.
    /// Constructor for creating new audit log entries. Id is generated by the database.
    /// </summary>
    /// <param name="objectKey">The object key/entity type.</param>
    /// <param name="event">The event/action type.</param>
    /// <param name="objectItemId">The affected entity ID.</param>
    /// <param name="ip">The IP address.</param>
    /// <param name="data">The audit data.</param>
    /// <param name="createdBy">The user who performed the action.</param>
    /// <remarks>TenantId is assigned automatically in ApplicationDbContext before saving.</remarks>
    public AuditLog(string objectKey, string @event, int objectItemId, string ip, string? data, int createdBy)
    {
        ObjectKey = objectKey;
        Event = @event;
        ObjectItemId = objectItemId;
        IP = ip;
        Data = data;
        CreatedAt = DateTime.UtcNow;
        CreatedBy = createdBy;
    }
}
