using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using OXDesk.Core.Entities;

namespace OXDesk.Core.AuditLogs;

/// <summary>
/// Represents an audit log entry in the CRM system.
/// Pure domain entity for tracking system activities.
/// Append-only entity - no updates or soft deletes.
/// </summary>
[Table("audit_logs")]
public class AuditLog : CreationAuditedEntity, IEntityGuid
{
    /// <summary>
    /// Gets or sets the unique identifier for the audit log entry.
    /// </summary>
    [Key]
    [Column("id")]
    [Required]
    public Guid Id { get; set; }

    /// <summary>
    /// Gets or sets the object key/entity type that was affected.
    /// </summary>
    [Column("module")]
    [Required]
    [MaxLength(100)]
    public string ObjectKey { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the event/action that occurred.
    /// </summary>
    [Column("event")]
    [Required]
    [MaxLength(100)]
    public string Event { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the UUID of the entity that was affected (for Guid-based entities).
    /// </summary>
    [Column("mapped_id_uuid")]
    public Guid? ObjectItemIdUuid { get; set; }

    /// <summary>
    /// Gets or sets the integer ID of the entity that was affected (for int-based entities).
    /// </summary>
    [Column("mapped_id_int")]
    public int? ObjectItemIdInt { get; set; }

    /// <summary>
    /// Gets or sets the IP address from which the action was performed.
    /// </summary>
    [Column("ip")]
    [MaxLength(45)]
    public string IP { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the any data generated for the action.
    /// </summary>
    [Column("data")]
    [MaxLength(1000)]
    public string? Data { get; set; }

    // Audit fields inherited from CreationAuditedEntity:
    // - CreatedAt, CreatedBy (append-only, no updates)


    /// <summary>
    /// Initializes a new instance of the <see cref="AuditLog"/> class.
    /// Default constructor for Entity Framework and general use.
    /// </summary>
    public AuditLog() { }

    /// <summary>
    /// Initializes a new instance of the <see cref="AuditLog"/> class.
    /// Constructor for creating new audit log entries. Id is generated by the database.
    /// </summary>
    /// <param name="objectKey">The object key/entity type.</param>
    /// <param name="event">The event/action type.</param>
    /// <param name="objectItemId">The affected entity ID (Guid).</param>
    /// <param name="ip">The IP address.</param>
    /// <param name="data">The audit data.</param>
    /// <param name="createdBy">The user who performed the action.</param>
    /// <remarks>TenantId is assigned automatically in ApplicationDbContext before saving.</remarks>
    public AuditLog(string objectKey, string @event, Guid objectItemId, string ip, string? data, Guid createdBy)
    {
        ObjectKey = objectKey;
        Event = @event;
        ObjectItemIdUuid = objectItemId;
        IP = ip;
        Data = data;
        CreatedAt = DateTime.UtcNow;
        CreatedBy = createdBy;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="AuditLog"/> class.
    /// Constructor for creating new audit log entries with int-based entity ID.
    /// </summary>
    /// <param name="objectKey">The object key/entity type.</param>
    /// <param name="event">The event/action type.</param>
    /// <param name="objectItemId">The affected entity ID (int).</param>
    /// <param name="ip">The IP address.</param>
    /// <param name="data">The audit data.</param>
    /// <param name="createdBy">The user who performed the action.</param>
    /// <remarks>TenantId is assigned automatically in ApplicationDbContext before saving.</remarks>
    public AuditLog(string objectKey, string @event, int objectItemId, string ip, string? data, Guid createdBy)
    {
        ObjectKey = objectKey;
        Event = @event;
        ObjectItemIdInt = objectItemId;
        IP = ip;
        Data = data;
        CreatedAt = DateTime.UtcNow;
        CreatedBy = createdBy;
    }
}
